- implants/eldritch/Cargo.toml
This PR fixes an issue with the upstream star-lark crate.
Here is the modified code base the backtrace function was modified to compile under `nightly-2021-11-22`
https://github.com/hulto/starlark-rust/tree/v0.6.0-patch
Fixes #47
> Switched to private fork of starlark with patch.

- implants/eldritch/Cargo.toml
/kind bug
Eldritch CI is failing. Git commit for private starlark disappeared recreated PRing.
https://github.com/hulto/starlark-rust/tree/v0.6.0-p1
> Old commit disapeared.... Reapplied patch

- implants/eldritch/src/process/list_impl.rs
/kind bug
/kind cleanup
Removes print statements from eldritch `proc.list`
> Removed prints statements.

- implants/eldritch/Cargo.toml
- implants/eldritch/src/file/download_impl.rs
/kind bug
This PR moves eldritch `file.download` to an async function using streams to write large files to disk. This will reduce the amount of bytes the program holds in memory at one time allowing us to write larger files to disk.
Fixes: #39
> Eldritch download stream

- docs/_docs/user-guide/eldritch.md
- implants/eldritch/src/file.rs
- implants/eldritch/src/file/is_file_impl.rs
- implants/eldritch/src/lib.rs
/kind feature
This PR adds a `file.is_file` feature to eldritch.
Fixes #61
> 61 feature eldritch fileis file

- tavern/graphql/generated/inputs.generated.go
- tavern/graphql/generated/mutation.generated.go
- tavern/graphql/generated/query.generated.go
- tavern/graphql/generated/root_.generated.go
- tavern/graphql/models/gqlgen_models.go
- tavern/graphql/mutation.resolvers.go
- tavern/graphql/schema/inputs.graphql
- tavern/graphql/schema/mutation.graphql
- tavern/graphql/session_test.go
- tavern/internal/www/schema.graphql
/kind feature
Adds the `submitTaskResult` mutation and related test, which will enable agents to report output (and errors) from task execution.
> Added SubmitTaskResult mutation and test

- tavern/graphql/job_test.go
- tavern/graphql/mutation.resolvers.go
- tavern/graphql/session_test.go
/kind bugfix
Updates two of our mutations (`claimTasks` and `createJob`) to reload ents that were created/updated with the transactional client before returning them. This is because when the transactional client is used to commit the transaction, it can no longer be used to load ents. For regular usage this was fine, but the bug was encountered when attempting to traverse edges on the result (see the example mutation below). This is because the returned ent(s) would have embedded the transactional `*ent.Client`, because that's the client they were loaded with. Further queries using that client would error, meaning additional graph traversals would fail like the example below:
```
mutation BugExample($sessionIDs: [ID!]!, $input: CreateJobInput!) {
createJob(sessionIDs: $sessionIDs, input: …
```
> [Tavern][bugfix] Fixed issue with transactional client

- implants/eldritch/src/pivot/port_scan_impl.rs
/kind bug
/kind cleanup
Portscanning has been causing other tests to fail. This test isn't needed.
Fixes #109
> Removed high resource portscan test.

- .github/workflows/docker.yml
- docker/tavern.Dockerfile
/kind feature
Adds a new Docker image for Tavern and adds a Github Workflow to publish the image to the Github Container Registery whenever a new release is created.
> [Tavern][CI] Added Tavern Production Docker Image (and release workflow)

- .github/workflows/tests.yml
- implants/eldritch/src/lib.rs
- implants/eldritch/src/sys/dll_inject_impl.rs
- implants/golem/src/main.rs
- implants/golem/tests/cli.rs
- implants/golem/working_dir/tomes/download_test.tome
- implants/imix/src/main.rs
- tests/create_file_dll/src/lib.rs
/kind bug
Async functions like download, and port_scan cause the agent to crash with an error about nested block_on runtimes.
To resolve this we've implemented new threads for each eldritch execution.
This creates a unique runtime for each allowing the eldritch function to create a tokio runtime.
Also resolves dll inject test failure by disabling defender in CI vms.
> Fix async eldritch functions crashing golem/imix.

- implants/golem/src/main.rs
- implants/imix/src/main.rs
/kind bug
PR improves the way imix and handles async connections tasks will no longer block the main thread or each other.
Fixes #182
> 182 eldritch sleep blocks imix agent

- implants/imix/src/main.rs
/kind bug
This PR resolves a deadlock issue around imix threads becoming exhausted when CPU core count # of threads have been spawned. Eg. a 4core system cannot have 4tasks that sleep 900 seconds and still perform imix check-ins.
The proposed change carries some nuance:
- spawns 128 threads that will run even when un-tasked creating an obvious artifact.
- If 128 blocking tasks are spawned the imix agent will again miss callbacks.
I believe the simplicity of the solution is worth the trade-offs.
Alternatives would be to implement a backlog queue, and ensure that only N-1 tasks are ever started at one time.
We could potentially also add a second runtime dedicated to the main loop but that would require re-designing the main_loop and adding complexity in the form of async channel …
> Increase the number of thread workers.

- implants/eldritch/src/lib.rs
- implants/golem/tests/cli.rs
/kind bug
/kind cleanup
This adds support for the case where parameters = "" this is the value when parameters is not specified by the c2 server.
Also adds improved error handling around parameter decoding.
This PR also adds error handling around other uses of `?` in eldritch_run to better show why tomes fail and hopefully speed up trouble shooting in the future.
Fixes #221
> Improved error message on parameters decode and "" case.

- implants/imix/src/main.rs
/kind bug
/kind cleanup
This PR will reduce the number of extraneous callbacks the agent makes to the c2.
Instead of sending an update to the server every callback seconds it will only send an update if the task has finished or has output to communicate.
Fixes #217
> Add check for task updates.

- .codecov.yml
Hopefully will prevent PR comments that cause -20% code coverage since CI pipelines haven't submitted their reports yet.
> Add codecov config to delay PR comment

- implants/Cargo.toml
- implants/lib/eldritch/Cargo.toml
- implants/lib/eldritch/src/sys/get_ip_impl.rs
Add one of the following kinds:
/kind cleanup
Limits use of the `network_interface` crate to windows only. Allows realm to be FreeBSD compatible.
N/A
> Differentiate IP Crate for Windows and Nix

- implants/lib/eldritch/src/file/compress_impl.rs
- implants/lib/eldritch/src/file/download_impl.rs
- implants/lib/eldritch/src/file/list_impl.rs
- implants/lib/eldritch/src/file/replace_all_impl.rs
- implants/lib/eldritch/src/pivot/arp_scan_impl.rs
- implants/lib/eldritch/src/pivot/ncat_impl.rs
- implants/lib/eldritch/src/pivot/ssh_exec_impl.rs
- implants/lib/eldritch/src/process/list_impl.rs
- implants/lib/eldritch/src/sys/exec_impl.rs
- implants/lib/eldritch/src/sys/get_ip_impl.rs
- implants/lib/eldritch/src/sys/get_os_impl.rs
- implants/lib/eldritch/src/sys/shell_impl.rs
/kind bug
- Resolves issues eldritch usage of expect which causes the process to panic.
- Removes dangerous calls to unwrap in eldritch
> Resolve expect crashes

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/process/name_impl.rs
modified:   docs/_docs/user-guide/eldritch.md
modified:   implants/lib/eldritch/src/process/name_impl.rs
/kind feature
Implement process.name as per #58
Fixes #58
> Implement process.name

- implants/lib/tavern/graphql/schema.graphql
- tavern/internal/graphql/generated/ent.generated.go
- tavern/internal/graphql/generated/root_.generated.go
- tavern/internal/graphql/schema.graphql
- tavern/internal/graphql/schema/query.graphql
- tavern/internal/graphql/testdata/queries/users/MeUnauthenticated.yml
- tavern/internal/graphql/testdata/queries/users/MeWithUnactivatedUser.yml
- tavern/internal/www/schema.graphql
/kind bug 
Allow unactivated users to perform the GraphQL `Me` query. This will enable the UI to query information about users who have not yet been approved by an administrator.
Fixes #339
> Allow unactivated users to query Me() graphql

- implants/imix/src/main.rs
/kind bug
Every time a windows imix instance starts, it makes a new UUID that causes more hosts in the DB. There was no Windows file path specified.
> Add Windows Path for system-id

- tavern/tomes/persist_service/metadata.yml
/kind bug
Adds the missing executable_url param to the service persit tome
> Add executable url param.

- .gitignore
- docs/_docs/dev-guide/tavern.md
- tavern/app.go
- tavern/config.go
/kind feature
This PR adds the new `ENABLE_PPROF` environment variable. When enabled, Tavern will register `pprof` endpoints and profiling will be enabled. Updates the documentation to provide examples on how to collect performance profiles.
> [Feature] Enable Tavern Performance Profiling

- tavern/internal/graphql/query.resolvers.go
- tavern/test_data.go
/kind bug
Recently, we encountered performance issues with large cardinality data-sets (reproducible with 50 quests, 900 tasks, 900 beacons, 300 hosts). This was due to the [N+1 Query Problem](https://entgo.io/docs/tutorial-todo-gql-field-collection/#problem). We had thought that EntGo would solve this issue for us, but as it turns out, we had to manually call `CollectFields` on each of our root level queries in order to enable eager-loading.  We also updated the test data in order to create a large enough dataset to reproduce the issue.
> [bugfix] fix n+1 query problem, manually specify CollectFields

- tavern/test_data.go
/kind bug
Reduces the amount of test data created so the UI doesn't break. When we add pagination (planned feature) then we can revert this change.
> [bugfix] Reduce amount of test data

- tavern/internal/c2/server.go
- tavern/internal/c2/testdata/claimTasks/NoTasks.yml
- tavern/internal/ent/beacon.go
- tavern/internal/ent/beacon/beacon.go
- tavern/internal/ent/beacon/where.go
- tavern/internal/ent/beacon_create.go
- tavern/internal/ent/beacon_update.go
- tavern/internal/ent/gql_collection.go
- tavern/internal/ent/gql_pagination.go
- tavern/internal/ent/gql_where_input.go
- tavern/internal/ent/migrate/schema.go
- tavern/internal/ent/mutation.go
- tavern/internal/ent/schema/beacon.go
- tavern/internal/graphql/generated/ent.generated.go
- tavern/internal/graphql/generated/mutation.generated.go
- tavern/internal/graphql/generated/root_.generated.go
- tavern/internal/graphql/generated/scalars.generated.go
- tavern/internal/graphql/gqlgen.yml
- tavern/internal/graphql/schema.graphql
- tavern/internal/graphql/schema/ent.graphql
- tavern/internal/graphql/schema/scalars.graphql
- tavern/internal/graphql/testdata/queries/beacons/Singular.yml
- tavern/internal/www/schema.graphql
Adds a new `Interval` field to the `Beacon`, which will enable clients to estimate the next expected check-in time. It will also provide some more information about the frequency of callbacks, so that users can further distinguish between `Beacons`. This required adding a new Uint64 scalar to our GraphQL schema.
Fixes #394
> [feature] Added new Uint64 GraphQL scalar, added Interval field to Beacon

- implants/imix/src/init.rs
- implants/lib/eldritch/src/assets/copy_impl.rs
- implants/lib/eldritch/src/pivot.rs
- implants/lib/eldritch/src/pivot/ncat_impl.rs
- implants/lib/eldritch/src/pivot/port_scan_impl.rs
- implants/lib/eldritch/src/pivot/ssh_copy_impl.rs
- implants/lib/eldritch/src/pivot/ssh_exec_impl.rs
/kind bug
/kind cleanup
Removes functions from port_scan that would panic.
Fixes #363
> Replace panicy functions with options and results.

- implants/golem/Cargo.toml
- implants/imix/Cargo.toml
- implants/lib/c2/Cargo.toml
- implants/lib/eldritch/Cargo.toml
- implants/lib/eldritch/build.rs
- implants/lib/eldritch/src/sys/dll_reflect_impl.rs
- tavern/version.go
> Fix build macro and increment build number.

- tavern/tomes/process_list/main.eldritch
/kind bug
Update the process list tome for the output to look like the following -
```bash
PID             PPID            username                        command
53              1               root                            /lib/systemd/systemd-udevd
428             354             ubuntu                          -bash
```
Hulto: Gonna change 423 to different tome editing so the issue stays open.
> Updated process list tome output (#423)

- tavern/tomes/process_tree/main.eldritch
- tavern/tomes/process_tree/metadata.yml
/kind bug
Created a new tome for printing process list as a tree. Process list will be output in the following format - 
```bash
PID             PPID            username                        command
1               0               root                            /lib/systemd/systemd --system --deserialize 44
2               1               root                             \_ /init
5               2               root                               \_ plan9 --control-socket 6 --log-level 4 --server-fd 7 --pipe-fd 9 --log-truncate
542             2               root                               \_ /init
349448          2               root                               \_ /init
354             2               root                               \_ /bin/login -f
349435          2 …
```
> Added new tome for printing process list as a tree (#423)

- implants/imix/src/tasks.rs
- implants/lib/eldritch/src/sys/write_reg_hex_impl.rs
- implants/lib/eldritch/src/sys/write_reg_int_impl.rs
- implants/lib/eldritch/src/sys/write_reg_str_impl.rs
/kind cleanup
NO MORE PROBLEMS
> fixed all the problems

- implants/lib/c2/src/c2_manual.rs
/kind bug
for using the fun new method
> adds the new method to the manual client

- tavern/internal/c2/c2pb/enum_host_platform_test.go
- tavern/internal/c2/c2pb/enum_process_status_test.go
/kind cleanup
Adds some more testing for our new pb enum types.
Fixes #
> [cleanup] Additional Enum Tests

- tavern/tomes/remove_file/main.eldritch
- tavern/tomes/remove_file/metadata.yml
/kind feature
Add new tome for deleting files/directories
Fixes #489
Let me know if any of the metadata values need changing. Also wasn't sure what the newline padding is for but I assume it's convention. I did a quick test in the dev container and it successfully removed both files and directories.
> Add file/directory removal tome

- tavern/tomes/get_env/main.eldritch
- tavern/tomes/get_env/metadata.yml
/kind feature
Adds tome for printing out environment variables
Fixes #491
> Add tome for printing environment variables

- tavern/tomes/get_net_info/main.eldritch
- tavern/tomes/get_net_info/metadata.yml
/kind feature
Tome for printing hostname and interfaces
Fixes #492
> Added get_net_info tome

- docs/_docs/dev-guide/eldritch.md
- docs/_docs/dev-guide/introduction.md
- docs/_docs/user-guide/eldritch.md
- docs/_docs/user-guide/imix.md
- docs/_docs/user-guide/tavern.md
- Updated tavern documentation for creating quests
- Tweaked some grammar
- Corrected some spelling mistakes/typos.
NA
> Documentation typo/spelling corrections

- docs/_docs/user-guide/getting-started.md
- docs/_docs/user-guide/imix.md
Updates documentations to reflect the fact that we've removed a config file.
> [docs] Update Imix Docs

- implants/golem/src/main.rs
- implants/golem/tests/cli.rs
- implants/lib/eldritch/src/runtime.rs
- tavern/tomes/file_tree/main.eldritch
/kind cleanup
Remove unused output from file tree output.
Output is now:
```
Running `/workspaces/realm/implants/target/debug/golem /workspaces/realm/tavern/tomes/get_net_info/main.eldritch`
Interfaces:
name: lo
ip: 127.0.0.1/8
mac: 00:00:00:00:00:00
name: eth0
ip: 172.17.0.2/16
mac: 02:42:ac:11:00:02
Hostname: 372a47305e3c
```
Instead of:
```
Running `/workspaces/realm/implants/target/debug/golem /workspaces/realm/tavern/tomes/get_net_info/main.eldritch`
OUTPUT: ["Interfaces:\n\n", "name: lo\n", "ip: 127.0.0.1/8\n", "mac: 00:00:00:00:00:00\n", "\n", "name: eth0\n", "ip: 172.17.0.2/16\n", "mac: 02:42:ac:11:00:02\n", "\n", "Hostname: 372a47305e3c", "\n", "\n"]
["Interfaces:\n\n", "name: lo\n", "ip: 127.0.0.1/8\n", "mac: 00:00:00:00:00:00\n", "\n", "name: eth0\n", "ip: 172.17.0.2/16\n", …
```
> 513 update file tree tome to default exclude extraneous dirs

- .devcontainer/devcontainer.json
- .vscode/settings.json
It was causing holding a write lock on the files for too long making iteration annoying.
/kind bug
Save @hulto's sanity.
> Removes the clippy fix on save

- tavern/app.go
fixes an nil pointer deref that occurs when the metrics server is not created and binding to port fails.
fixes an error that occurs when following the readme as a non root user.
Fixes #
> [bug] Fix metrics nil ptr deref on close

- .github/workflows/tests.yml
- implants/imix/src/task.rs
- implants/lib/eldritch/Cargo.toml
- implants/lib/eldritch/src/assets.rs
- implants/lib/eldritch/src/assets/copy_impl.rs
- implants/lib/eldritch/src/runtime/exec.rs
/kind feature
Adds remote files to the `assets.copy` function allowing more seemless tome development for golem and imix.
Fixes #421
> Implement assets remote api

- implants/imix/src/task.rs
- implants/lib/c2/Cargo.toml
- implants/lib/c2/src/grpc.rs
- implants/lib/eldritch/src/assets/copy_impl.rs
- tavern/internal/c2/c2test/grpc.go
- tavern/tomes/example/main.eldritch
/kind bug
Fixes our assets.copy implementation, as well as an issue with how imix was downloading files for tasks.
> [bug] Fix file download

- implants/lib/eldritch/src/lib.rs
- implants/lib/eldritch/src/report/mod.rs
- implants/lib/eldritch/src/report/process_list_impl.rs
- implants/lib/eldritch/src/runtime/exec.rs
- tavern/internal/ent/schema/host_process.go
- tavern/internal/graphql/ent.resolvers.go
- tavern/internal/graphql/generated/ent.generated.go
- tavern/internal/graphql/generated/root_.generated.go
- tavern/internal/graphql/gqlgen.yml
- tavern/internal/graphql/schema.graphql
- tavern/internal/graphql/schema/ent.graphql
- tavern/internal/www/schema.graphql
/kind feature
Enables us to report process lists, also fixes an entgo generation bug with HostProcess.
Fixes #
> [feature] Process List Reporting

- .devcontainer/library-scripts/rust-debian.sh
- .github/workflows/release.yml
- .github/workflows/tests.yml
- bin/create_file_dll/rust-toolchain
- bin/reflective_loader/rust-toolchain
- implants/Cargo.toml
- implants/golem/Cargo.toml
- implants/golem/src/inter/eval.rs
- implants/golem/src/inter/types.rs
- implants/lib/eldritch/src/file/follow_impl.rs
- implants/lib/eldritch/src/lib.rs
- implants/lib/eldritch/src/pivot.rs
- implants/lib/eldritch/src/pivot/port_scan_impl.rs
- implants/lib/eldritch/src/process/info_impl.rs
- implants/lib/eldritch/src/process/list_impl.rs
- implants/lib/eldritch/src/process/netstat_impl.rs
- implants/lib/eldritch/src/report/mod.rs
- implants/lib/eldritch/src/runtime/exec.rs
- implants/lib/eldritch/src/sys.rs
- implants/lib/eldritch/src/sys/dll_reflect_impl.rs
- implants/lib/eldritch/src/sys/get_env_impl.rs
- implants/lib/eldritch/src/sys/get_reg_impl.rs
- implants/lib/eldritch/src/sys/get_user_impl.rs
- implants/lib/eldritch/src/sys/shell_impl.rs
- implants/rust-toolchain
/kind cleanup
* Upgrades rust to 1.76.0
* Upgrades starlark to 0.12.0
> [cleanup] starlark -> 0.12.0, rust -> 1.76.0

- .github/workflows/release.yml
/kind devops
/kind bug
This _should_(?) _might_(?) fix windows builds for implants during releases.
Tested in #581 without uploading, so I don't know if it produces the correct bin, but it does finish the build without errors.
Fixes #
> Fix implants windows release workflow

- docs/_docs/dev-guide/eldritch.md
- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/lib.rs
- implants/lib/eldritch/src/regex/match_all_impl.rs
- implants/lib/eldritch/src/regex/match_impl.rs
- implants/lib/eldritch/src/regex/mod.rs
- implants/lib/eldritch/src/regex/replace_all_impl.rs
- implants/lib/eldritch/src/regex/replace_impl.rs
- implants/lib/eldritch/src/runtime/eval.rs
- implants/lib/eldritch/src/runtime/mod.rs
/kind feature
/kind eldritch-library
for our string-oriented fiends
Fixes QoL
> Regex-lib-stub

- docs/_docs/user-guide/imix.md
- implants/Cargo.toml
- implants/imix/Cargo.toml
- implants/imix/src/install.rs
- implants/imix/src/lib.rs
- implants/imix/src/main.rs
- implants/imix/src/win_service.rs
- implants/lib/transport/src/grpc.rs
/kind feature
Allows imix to compile to a windows service exe.
Fixes #375
> Adds support to be compiled as a windows service.

- implants/golem/src/inter/eval.rs
- implants/lib/eldritch/src/pivot/port_scan_impl.rs
- implants/lib/eldritch/src/runtime/eval.rs
- implants/lib/eldritch/src/sys/dll_reflect_impl.rs
- implants/lib/eldritch/src/sys/shell_impl.rs
- vscode/eldritch-lang/src/eval.rs
/kind feature
Life, Liberty, and the pursuit of f"reedom
> Enable f-strings for fun

- bin/embedded_files_test/exec_script/metadata.yml
- bin/embedded_files_test/print/metadata.yml
- tavern/internal/ent/schema/repository.go
- tavern/internal/graphql/testdata/mutations/createRepository/URLWithHTTPS.yml
- tavern/tomes/git.go
- tavern/tomes/parse.go
/kind bug
Fix imports of public repos via https
> [bug] Fix https public repo imports

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/http/get_impl.rs
- implants/lib/eldritch/src/http/mod.rs
- implants/lib/eldritch/src/http/post_impl.rs
- implants/lib/eldritch/src/runtime/mod.rs
/kind feature
It will be useful to issue HTTP GET requests from imix.
> Added the `http.get` and `http.post` functions with query params, headers, form, bodies as optional params (depending on GET vs POST)

- implants/lib/eldritch/src/assets/copy_impl.rs
- implants/lib/eldritch/src/crypto/hash_file_impl.rs
/kind bug
Prevent assets.copy() from truncating the destination file if we fail to fetch the asset.
> [bug] Prevent assets.copy() truncating file when fetch_asset fails

- implants/lib/eldritch/src/file/read_impl.rs
- implants/lib/eldritch/src/runtime/eval.rs
> Remove lint warns

- implants/imix/src/install.rs
- implants/imix/src/task.rs
- implants/lib/eldritch/src/file/read_impl.rs
- implants/lib/eldritch/src/runtime/messages/mod.rs
/kind bug
Derive "Display" even in release builds as it is now sent as part of error reporting.
> [bug] Fix display for message

- implants/imix/src/install.rs
- implants/imix/src/task.rs
- implants/lib/eldritch/src/assets/copy_impl.rs
/kind bug
Updates `assets.copy` to remove files instead of truncating them. This will prevent the error "Text file busy (os error 26)" when attempting to overwrite a file that is currently in use by a running process.
> [bug] Remove file for assets.copy() instead of truncating

- tavern/internal/auth/oauth.go
- tavern/internal/auth/oauth_test.go
/kind bug
Our `/oauth/authorize` endpoint is setup to create new user accounts (based on oauth state) and redirect users to the application. However, it was not redirecting users with existing user accounts signing in for the first time from a new device. This PR addresses that issue.
Fixes #653
> [bug] Redirect existing users on new login

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/Cargo.toml
- implants/lib/eldritch/src/sys/get_ip_impl.rs
/kind cleanup
/kind feature
Add netmask CIDR to sys.get_ip
Remove get_ip dependency on `pnet` crate.
Unblocks #484
> Add netmask to get ip

- implants/lib/eldritch/build.rs
- implants/lib/eldritch/src/file/list_impl.rs
- implants/lib/eldritch/src/pivot/arp_scan_impl.rs
- implants/lib/eldritch/src/sys/dll_inject_impl.rs
- implants/lib/eldritch/src/sys/dll_reflect_impl.rs
- implants/lib/eldritch/src/sys/get_ip_impl.rs
- implants/lib/eldritch/src/sys/get_reg_impl.rs
- implants/lib/eldritch/src/sys/write_reg_hex_impl.rs
- implants/lib/eldritch/src/sys/write_reg_int_impl.rs
- implants/lib/eldritch/src/sys/write_reg_str_impl.rs
> Cleanup windows lint warnings

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/file/mkdir_impl.rs
- implants/lib/eldritch/src/file/mod.rs
- tavern/tomes/download/main.eldritch
- tavern/tomes/file_mkdir/main.eldritch
- tavern/tomes/file_mkdir/metadata.yml
/kind feature
Rayne NEEDS this
> Added a `file.mkdir` tome and also added a `parent` param similar to linux's 

- tavern/internal/www/src/components/TomeAccordion.tsx
- tavern/internal/www/src/pages/create-quest/components/TomeRadioGroup.tsx
- tavern/internal/www/src/pages/quest-list/QuestList.tsx
- tavern/internal/www/src/pages/tomes/components/RepositoryTable.tsx
- tavern/internal/www/src/style.css
/kind bug
- Fixes some of the responsive issues so things display better on mobile. Kids love hacking on mobile.
- Adding spacing for vertical spacing for quests
- Changed language on tome tables
- Added break-all styling to links
> fix(style): Fix styling of quest and tomes

- docs/_docs/user-guide/tomes.md
- tavern/app.go
/kind bug 
When Cloud Run spins up a new container, it will try to upload the default tomes again. This will fail, because the tomes already exist. This change simply logs an error for the default tomes and then continues onward. In the future, it's worth considering removing the default tomes altogether and just providing them via git.
> [bug] Fix fatal on default tome upload

- .vscode/settings.json
- implants/imix/src/agent.rs
- implants/imix/src/config.rs
/kind bug
As documented in #704, we were seeing that Imix would sometimes check in faster than the networking stack would complete DHCP on some boxes. To solve this we will just refresh our `primary_ip` with each callback.
Fixes #704
> Get Agent IP every callback

- tavern/tomes/file_write/main.eldritch
- tavern/tomes/file_write/metadata.yml
/kind feature
We never exposed the `file.write` function to a tome. Which is useful.
Fixes #710
> File Write Tome

- tavern/app.go
/kind bug
Allows `/graphql` and `/cdn/` endpoints to be accessed by unactivated users. In the case of GraphQL, it performs it's own authorization such that unactivated users can run the `me` query and see their own information. For `/cdn/` only file downloads may be unauthenticated and unactivated, since currently Agents do not perform any authentication.
> [bug] Allow GraphQL & CDN to be accessed by unactivated users

- implants/lib/eldritch/src/assets/list_impl.rs
- implants/lib/eldritch/src/assets/mod.rs
- implants/lib/eldritch/src/assets/read_binary_impl.rs
- implants/lib/eldritch/src/assets/read_impl.rs
- implants/lib/eldritch/src/file/replace_all_impl.rs
- implants/lib/eldritch/src/file/replace_impl.rs
- implants/lib/eldritch/src/file/template_impl.rs
/kind bug
/kind feature
This PR adds support for reading binary files and adds remote support to the remaining asset functions:
- read
- read_binary
- list
Fixes #725
> Binary read support

- terraform/main.tf
/kind cleanup
Stops terraform from disabling GCP apis on delete.
GCP doesn't do a great job disabling and enabling APIs which can result in them entering an unknown state for up to 3 days.
To avoid this behavior we should prevent terraform from disabling on destroy especially since people may wish to deploy other infrastructure under this project as well.
Fixes #738
> Don't disable apis on disable.

- implants/imix/src/config.rs
/kind bug
`/etc` was only writeable by root sogonna swap over to allow non root users to still get host uniqueness.
> Use world writeable paths

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/random/mod.rs
- implants/lib/eldritch/src/random/string_impl.rs
- implants/lib/eldritch/src/runtime/mod.rs
/kind feature
Adds random.string(uint) to eldritch to allow tome developers to generate random strings.
N/A
> feat: add random.string function to eldritch

- tavern/tomes/fetch_asset/main.eldritch
- tavern/tomes/fetch_asset/metadata.yml
- tavern/tomes/http_get_file/main.eldritch
- tavern/tomes/http_get_file/metadata.yml
- tavern/tomes/http_get_file_and_execute/main.eldritch
- tavern/tomes/http_get_file_and_execute/metadata.yml
- tavern/tomes/report_file/main.eldritch
- tavern/tomes/report_file/metadata.yml
Renames tomes away from upload / download
Adds fetch and report file tomes.
make tome activity more clear
> Ban upload / download

- docs/_data/toc.yml
- docs/_docs/dev-guide/imix.md
- docs/_docs/user-guide/imix.md
- implants/Cargo.toml
- implants/imix/Cargo.toml
- implants/imix/src/config.rs
- implants/lib/host_unique/Cargo.toml
- implants/lib/host_unique/src/env.rs
- implants/lib/host_unique/src/file.rs
- implants/lib/host_unique/src/lib.rs
Add one of the following kinds:
/kind feature
This PR provides greater control to admins when deploying the imix agent around how the uniqueness of a host is determined. In most red teaming situations writing a file to disk is unideal and the tradeoffs to use something else like mac address are worth it. This PR adds an environment variable override to the host ID and makes it easier for admins to implement and add their own uniqueness.
Fixes #781
> Make host uniqueness modular

- terraform/main.tf
/kind feature
Updates terraform to correctly configure the service to support distributed reverse shells.
> [Tavern] Terraform Reverse Shells

- go.mod
- tavern/app.go
- tavern/config.go
…tavern instance
/kind bug
Updates Tavern to connect and create a new unique pubsub subscription for each instance of Tavern. The subscriptions are currently configured to expire after 1 day of inactivity. This is necessary because GCP Pubsub load-balances messages across all subscribers that share the same subscription, meaning for reverse shells when multiple instances of tavern are running they each only get a fragment of the messages (and therefore the shell works very poorly with more than one running instance). Read more here: https://cloud.google.com/pubsub/docs/pubsub-basics#choose_a_publish_and_subscribe_pattern
> [Tavern] Create Unique Pubsub Subscriptions

- tavern/config.go
> [Tavern] log pubsub error

- tavern/config.go
> [Tavern] Fix GCPPubsub Topic ID

- tavern/config.go
> [Tavern] Format GCPPubsub topic ID

- tavern/config.go
> [Tavern] Correct GCP Subscription Prefix

- docs/_docs/user-guide/eldritch.md
- tavern/tomes/netstat/main.eldritch
/kind cleanup
- Fix netstat output
- Update docs on temp file
- Update docs regarding UNC paths
Fixes #
> Small fixes

- tavern/config.go
- tavern/internal/http/stream/gcp_coldstart.go
/kind feature
Creates a go routine to publish noop messages on an interval to help avoid cold start latency.
> [Tavern] Fix GCP PubSub ColdStart Latency

- implants/lib/host_unique/src/file.rs
/kind bug
- Fixes host id bug resulting in always new beacons
> Fix file uniqueness string not bytes.

- bin/ccdc-team-mappings/create_tags.py
- bin/cred-publishing/creds.py
/kind feature
- Publish creds to realm form text file in format `ip:user:pass`
Fixes #
> Cred poster

- tavern/app.go
- tavern/config.go
- tavern/env.go
- tavern/env_test.go
- tavern/log.go
- terraform/main.tf
/kind cleanup
* Adds `EnvBool` to represent boolean values
* Updates how we log unset environment variables to a uniform style warning that configuration is missing
* Makes the default logger use text output (via `ENABLE_JSON_LOGGING`)
* Updated terraform to enable this by default 
* Defaults to excluding the tavern instance id from logs (via `ENABLE_INSTANCE_ID_LOGGING`)
* Updated terraform to enable this by default
* Allows graphql raw query logging (via `ENABLE_GRAPHQL_RAW_QUERY_LOGGING`)
* Updated terraform to enable this by default
* Adds `EnvBool` testing
> [Tavern] Add EnvBool and Update Default Config

- .github/workflows/release.yml
Fixes our github release workflow
> [Github] Fix release workflow

- .github/workflows/release.yml
Compile macOS release assets for arm
> [Github] Change macos release assets to arm

- implants/imix/install_scripts/install_service/main.eldritch
- implants/lib/pb/src/generated/c2.rs
/kind cleanup
just to keep our macOS persistence tidy
> Fixed up install script for macOS

- implants/lib/eldritch/Cargo.toml
- implants/lib/eldritch/src/sys/shell_impl.rs
/kind bug
Resolves issues with windows shell arguments being parsed incorrectly.
> fix shell for windows

- tavern/internal/c2/api_claim_tasks.go
- tavern/internal/ent/gql_collection.go
- tavern/internal/ent/gql_where_input.go
- tavern/internal/ent/host.go
- tavern/internal/ent/host/host.go
- tavern/internal/ent/host/where.go
- tavern/internal/ent/host_create.go
- tavern/internal/ent/host_update.go
- tavern/internal/ent/migrate/schema.go
- tavern/internal/ent/mutation.go
- tavern/internal/ent/schema/host.go
- tavern/internal/graphql/generated/ent.generated.go
- tavern/internal/graphql/generated/mutation.generated.go
- tavern/internal/graphql/generated/root_.generated.go
- tavern/internal/graphql/schema.graphql
- tavern/internal/graphql/schema/ent.graphql
- tavern/internal/www/schema.graphql
/kind feature
Folks displayed an interest in having the external IP of the host available. This change will log the incoming IP at an `externalIP` in the host.
If `X-Forwarded-For` is set, the first IP in the list will be used. Otherwise, the remote IP from the connection is used.
First Example using Direct Connection (VPN IP)
Second Example (GCP) using Header (VPN IP)
Fixes #879
> Add External IP Field to Hosts

- docs/_docs/admin-guide/tavern.md
> Added CDN docs

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/sys/exec_impl.rs
/kind bug
Allow `sys.exec` to run windows commands non-blocking by detaching stdout and stderr
Fixes #
> Windows backrgound exec

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/file/write_impl.rs
> Make file.write consistent with other methods and overwrite instead of error is "to" file exists

- docs/_docs/dev-guide/imix.md
- implants/imix/Cargo.toml
- implants/imix/src/agent.rs
- implants/imix/src/run.rs
- implants/lib/transport/Cargo.toml
- implants/lib/transport/src/grpc.rs
- implants/lib/transport/src/mock.rs
- implants/lib/transport/src/transport.rs
> Complete the initial Transport work... finally

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/sys/exec_impl.rs
- implants/lib/eldritch/src/sys/mod.rs
/kind feature
Put it as the last arg to avoid breaking any current tomes using disown positionally
> Adding EnvVars to `sys.exec` for fun

- tavern/internal/ent/schema/host_file.go
/kind bug
/kind feature
the operators yearn to report lsass memory dumps
> Allow Large files for HistFiles

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/agent/eval_impl.rs
- implants/lib/eldritch/src/agent/mod.rs
- implants/lib/eldritch/src/lib.rs
- implants/lib/eldritch/src/runtime/environment.rs
- implants/lib/eldritch/src/runtime/eval.rs
- implants/lib/eldritch/src/runtime/mod.rs
/kind feature
Need to write docs also :/
Idea is that the new `agent` module can be used for various meta-actions with the bot.
> Adding `agent.eval` that takes in arbitrary eldritch and executes it

- tavern/internal/c2/api_report_task_output.go
- tavern/internal/c2/api_report_task_output_test.go
/kind bug
Makes error an append instead of replace
Fixes #918
> report error append instead of replace

- implants/lib/eldritch/src/pivot/mod.rs
/kind bug
Don't error ssh_copy if dest file doesn't exist.
Fixes #917
> Don't error if remove_file fails.

- implants/lib/eldritch/src/pivot/port_scan_impl.rs
/kind bug
Another error case that denotes a closed port
> Add host unreachable error

- implants/imix/src/agent.rs
- tavern/tomes/arp_scan/main.eldritch
- tavern/tomes/file_list/main.eldritch
- tavern/tomes/file_mkdir/main.eldritch
- tavern/tomes/file_tree/main.eldritch
- tavern/tomes/file_write/main.eldritch
- tavern/tomes/get_env/main.eldritch
- tavern/tomes/get_net_info/main.eldritch
- tavern/tomes/get_registry/main.eldritch
- tavern/tomes/kill_process/main.eldritch
- tavern/tomes/netstat/main.eldritch
- tavern/tomes/process_info/main.eldritch
- tavern/tomes/process_list/main.eldritch
- tavern/tomes/process_tree/main.eldritch
- tavern/tomes/remove_file/main.eldritch
- tavern/tomes/shell_cmd/main.eldritch
/kind bug
It seems like the issue with tomes reporting back too fast is that there's no initial task reporting where the claimed at is set.
To solve this always send two reports.
Fixes #754
> Fix task reporting errors when I/O blocking tasks run

- docs/_docs/user-guide/eldritch.md
- implants/lib/eldritch/src/agent/mod.rs
- implants/lib/eldritch/src/agent/set_callback_uri_impl.rs
- implants/lib/eldritch/src/runtime/messages/mod.rs
- implants/lib/eldritch/src/runtime/messages/set_callback_uri.rs
- implants/lib/eldritch/src/runtime/mod.rs
Did not realize this was a hot commodity so quickly added it while troubleshooting my 3d printer.
/kind feature
> Adding `agent.set_callback_uri` method

- implants/Cargo.toml
- implants/golem/Cargo.toml
- implants/golem/build.rs
- implants/imix/Cargo.toml
- implants/imix/build.rs
/kind bug
Ran into issue where golem and imix would crash with error `VCRUNTIME140.dll` was not found.
Had to add specific configuration to statically compile `vcruntime`
Fixes #
> Windown vcruntime

- docs/_docs/user-guide/imix.md
- implants/imix/src/agent.rs
- implants/imix/src/run.rs
- implants/lib/pb/src/config.rs
> Add a Run Once capability to Imix

- tavern/internal/secrets/debug_file_test.go
> fix(tests): update secrets test to match new struct
